// CodeMirror 内置短语以原文为键，语言变化通过扩展重配置生效。
export const sourceEditorPhrases: Record<string, string> = {
  'Control character': '控制字符',
  'Selection deleted': '已删除选区',
  'Folded lines': '已折叠行',
  'Unfold': '展开',
  'Fold line': '折叠行',
  'Unfold line': '展开行',
  'Go to line': '跳转到行',
  'go': '跳转',
  'Find': '查找',
  'Replace': '替换',
  'next': '下一个',
  'previous': '上一个',
  'all': '全部',
  'match case': '区分大小写',
  'regexp': '正则表达式',
  'by word': '全词匹配',
  'replace': '替换',
  'replace all': '全部替换',
  'close': '关闭',
  'current match': '当前匹配',
  'replaced $ matches': '已替换 $ 处匹配',
  'replaced match on line $': '已替换第 $ 行的匹配',
  'on line': '所在行'
}
